repos:
  # Meta housekeeping to keep pre-commit operating correctly
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  # General housekeeping and auto-fixers
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: trailing-whitespace

  # Python import formatting
  - repo: https://github.com/asottile/seed-isort-config
    rev: v1.9.3
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
