version: "3.3"
services:
  db:
    image: "postgres:${POSTGRES_VER}"
    environment:
     - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
     - "POSTGRES_USER=${POSTGRES_USER}"
     - "POSTGRES_DB=${POSTGRES_DB}"

  pyshelf:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "${LOCAL_BOOK_DIR}:/usr/src/app/Books"
      - "./cron/root:/etc/crontabs/root"
      - "./scripts/wait-for-it.sh:/usr/src/app/src/"
    ports:
      - "${PORT}:8000"
    links:
      - "db:db"
    depends_on:
      - db
