version: "3.7"

services:
    db:
        image: "postgres"
        environment:
            - "POSTGRES_PASSWORD=pyshelf"
            - "POSTGRES_USER=pyshelf"
            - "POSTGRES_DB=pyshelf"
        volumes:
            - "pgdata:/var/lib/postgresql/data/"

    pyshelf:
        build:
            context: ..
            dockerfile: ./docker/Dockerfile
        ports: 
            - "8080:8000"
        volumes:
            - "../books:/books"
        depends_on:
            - db

volumes:
    pgdata: